location /.well-known/host-meta {
    # We don't want any ssowat checks here
    access_by_lua_block { return }
    
    # allow access from Prose (among others)
    more_set_headers "Access-Control-Allow-Origin: *"; 

    alias /var/www/.well-known/__DOMAIN__/host-meta;
}

# Expose BOSH and webscoket for XMPP
location /xmpp-bosh {
    # We don't want any ssowat checks here
    access_by_lua_block { return }

    proxy_pass http://localhost:5280/xmpp-bosh;

    include proxy_params_no_auth;
    proxy_buffering off;
    tcp_nodelay on;
}
location /xmpp-websocket {
    # We don't want any ssowat checks here
    access_by_lua_block { return }

    proxy_pass http://localhost:5280/xmpp-websocket;

    include proxy_params_no_auth;
    proxy_buffering off;
    tcp_nodelay on;
}
