#! /bin/bash

# This script is expected to be called xx-$app
app=$(basename $0 | cut -d- -f2)
domain=$(yunohost app setting $app domain)

# only add subdomains to the app's domain
if [[ "$domain"  != *"$base_domain" ]]; then
  exit 0
fi


echo "
- name: 'xmpp-upload${suffix}'
  ttl: 3600
  type: CNAME
  value: '${base_domain}.'
- name: 'muc${suffix}'
  ttl: 3600
  type: CNAME
  value: '${base_domain}.'
- name: 'pubsub${suffix}'
  ttl: 3600
  type: CNAME
  value: '${base_domain}.'
- name: '_xmpp-client._tcp${suffix}'
  ttl: 3600
  type: SRV
  value: '0 5 5222 ${base_domain}.'
- name: '_xmpps-client._tcp${suffix}'
  ttl: 3600
  type: SRV
  value: '0 5 5223 ${base_domain}.'
- name: '_xmpp-server._tcp${suffix}'
  ttl: 3600
  type: SRV
  value: '0 5 5269 ${base_domain}.'
" > ${YNH_STDRETURN}
