#! /bin/bash

# This script is expected to be called xx-$app
app=$(basename $0 | cut -d- -f2)
domain=$(yunohost app setting $app domain)

# only add subdomains to the app's domain
if [[ "$domain"  != *"$base_domain" ]]; then
  exit 0
fi


suffix="${base_domain}."
echo "
- name: 'xmpp-upload.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'muc.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'pubsub.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'vjud.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'proxy.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: '_xmpp-client._tcp'
  ttl: 3600
  type: SRV
  value: '0 5 5222 ${suffix}'
- name: '_xmpp-server._tcp'
  ttl: 3600
  type: SRV
  value: '0 5 5269 ${suffix}'
- name: '_xmpps-client._tcp'
  ttl: 3600
  type: SRV
  value: '0 5 5223 ${suffix}'
- name: '_xmpps-server._tcp'
  ttl: 3600
  type: SRV
  value: '0 5 5270 ${suffix}'
" > ${YNH_STDRETURN}
