#! /bin/bash

# This script is expected to be called xx-$app
app=$(basename $0 | cut -d- -f2)
domain=$(yunohost app setting $app domain)

# only add subdomains to the app's domain
if [[ "$domain"  != *"$base_domain" ]]; then
  exit 0
fi


suffix="${base_domain}."
echo "
- name: 'xmpp-upload.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'muc.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'pubsub.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
- name: 'vjud.${suffix}'
  ttl: 3600
  type: CNAME
  value: '${suffix}'
" > ${YNH_STDRETURN}
