#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#TODO: does not work if there is only 1 root domain
#domains=$(yunohost domain list --exclude-subdomains | grep -Ev '^(domains|main):' | awk '{print $2}')

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

rm /etc/prosody/conf.d/$domain.cfg.lua
rm /etc/prosody/conf.avail/$domain.cfg.lua
rm /etc/nginx/conf.d/$domain-extra-xmpp.conf

DEBIAN_FRONTEND=noninteractive apt-get remove --assume-yes prosody

yunohost tools regen-conf nginx

ynh_script_progression "Reloading nginx..."
ynh_systemctl --service="nginx" --action="reload"

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================

ynh_script_progression "Removing various files..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"

#TODO: notify that dependancy on coturn_ynh is not managed (kept)
