#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DISABLE METRONOME
#=================================================
ynh_script_progression "Disabling Metronome..."

if systemctl list-unit-files metronome.service &>/dev/null
then
	ynh_systemctl --service="metronome" --action="stop"
	systemctl disable metronome.service --quiet
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Installing prosody package from Debian..."

ynh_apt_install_dependencies prosody prosody-modules

#=================================================
# SPECIFIC SETUP
#=================================================

# Add permision to read certs
usermod -a -G ssl-cert prosody

#=================================================
# RESTORE THE CONFIG DIR
#=================================================
ynh_script_progression "Restoring the config directory..."

ynh_restore "$config_path"
chmod 755 /etc/prosody

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "/var/lib/$app" || true
chmod 755 "/var/lib/$app"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Restoring the logrotate configuration..."

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --log=/var/log/$app/$app.log --needs_exposed_ports $port_client $port_client2 $port_server

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Restarting the systemd service..."

# Restart the systemd service
ynh_systemctl --service=$app --action="restart"

#=================================================
# RESTORE CUSTOM NGINX CONFIG
#=================================================

cp -R "$YNH_APP_BASEDIR/conf/hook_conf_regen" "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"
YNH_HELPERS_VERSION=1 yunohost tools regen-conf nginx

ynh_script_progression "Reloading nginx..."
ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
